### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by leetut** [n3ws/fvduino#1]
fvduino.ino won't compile for me, any ideas?

`Arduino: 1.8.13 (Mac OS X), Board: "ATmega328, Yes (UART0), EEPROM retained, 328P / 328PA, BOD 2.7V, LTO disabled, External 16 MHz"

/Applications/Arduino.app/Contents/Java/arduino-builder -dump-prefs -logger=machine -hardware /Applications/Arduino.app/Contents/Java/hardware -hardware /Users/lee/Library/Arduino15/packages -hardware /Users/lee/Documents/Arduino/hardware -tools /Applications/Arduino.app/Contents/Java/tools-builder -tools /Applications/Arduino.app/Contents/Java/hardware/tools/avr -tools /Users/lee/Library/Arduino15/packages -built-in-libraries /Applications/Arduino.app/Contents/Java/libraries -libraries /Users/lee/Documents/Arduino/libraries -fqbn=MiniCore:avr:328:bootloader=uart0,eeprom=keep,variant=modelP,BOD=2v7,LTO=Os,clock=16MHz_external -ide-version=10813 -build-path /var/folders/kz/yg8fjhp53c3201sw0bhpccy40000gn/T/arduino_build_304102 -warnings=none -build-cache /var/folders/kz/yg8fjhp53c3201sw0bhpccy40000gn/T/arduino_cache_133690 -prefs=build.warn_data_percentage=75 -verbose /Users/lee/Desktop/fvduino-main/fvduino/fvduino.ino
/Applications/Arduino.app/Contents/Java/arduino-builder -compile -logger=machine -hardware /Applications/Arduino.app/Contents/Java/hardware -hardware /Users/lee/Library/Arduino15/packages -hardware /Users/lee/Documents/Arduino/hardware -tools /Applications/Arduino.app/Contents/Java/tools-builder -tools /Applications/Arduino.app/Contents/Java/hardware/tools/avr -tools /Users/lee/Library/Arduino15/packages -built-in-libraries /Applications/Arduino.app/Contents/Java/libraries -libraries /Users/lee/Documents/Arduino/libraries -fqbn=MiniCore:avr:328:bootloader=uart0,eeprom=keep,variant=modelP,BOD=2v7,LTO=Os,clock=16MHz_external -ide-version=10813 -build-path /var/folders/kz/yg8fjhp53c3201sw0bhpccy40000gn/T/arduino_build_304102 -warnings=none -build-cache /var/folders/kz/yg8fjhp53c3201sw0bhpccy40000gn/T/arduino_cache_133690 -prefs=build.warn_data_percentage=75 -verbose /Users/lee/Desktop/fvduino-main/fvduino/fvduino.ino
Using board '328' from platform in folder: /Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6
Using core 'MCUdude_corefiles' from platform in folder: /Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6
Detecting libraries used...
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10813 -DARDUINO_AVR_ATmega328 -DARDUINO_ARCH_AVR -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/cores/MCUdude_corefiles -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/variants/standard /var/folders/kz/yg8fjhp53c3201sw0bhpccy40000gn/T/arduino_build_304102/sketch/fvduino.ino.cpp -o /dev/null -DARDUINO_LIB_DISCOVERY_PHASE
Alternatives for Bounce2.h: [Bounce2@2.53]
ResolveLibrary(Bounce2.h)
  -> candidates: [Bounce2@2.53]
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10813 -DARDUINO_AVR_ATmega328 -DARDUINO_ARCH_AVR -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/cores/MCUdude_corefiles -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/variants/standard -I/Users/lee/Documents/Arduino/libraries/Bounce2/src /var/folders/kz/yg8fjhp53c3201sw0bhpccy40000gn/T/arduino_build_304102/sketch/fvduino.ino.cpp -o /dev/null -DARDUINO_LIB_DISCOVERY_PHASE
Alternatives for EEPROM.h: [EEPROM@2.0]
ResolveLibrary(EEPROM.h)
  -> candidates: [EEPROM@2.0]
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10813 -DARDUINO_AVR_ATmega328 -DARDUINO_ARCH_AVR -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/cores/MCUdude_corefiles -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/variants/standard -I/Users/lee/Documents/Arduino/libraries/Bounce2/src -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/libraries/EEPROM/src /var/folders/kz/yg8fjhp53c3201sw0bhpccy40000gn/T/arduino_build_304102/sketch/fvduino.ino.cpp -o /dev/null -DARDUINO_LIB_DISCOVERY_PHASE
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10813 -DARDUINO_AVR_ATmega328 -DARDUINO_ARCH_AVR -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/cores/MCUdude_corefiles -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/variants/standard -I/Users/lee/Documents/Arduino/libraries/Bounce2/src -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/libraries/EEPROM/src /var/folders/kz/yg8fjhp53c3201sw0bhpccy40000gn/T/arduino_build_304102/sketch/oled.cpp -o /dev/null -DARDUINO_LIB_DISCOVERY_PHASE
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10813 -DARDUINO_AVR_ATmega328 -DARDUINO_ARCH_AVR -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/cores/MCUdude_corefiles -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/variants/standard -I/Users/lee/Documents/Arduino/libraries/Bounce2/src -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/libraries/EEPROM/src /Users/lee/Documents/Arduino/libraries/Bounce2/src/Bounce2.cpp -o /dev/null -DARDUINO_LIB_DISCOVERY_PHASE
Generating function prototypes...
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10813 -DARDUINO_AVR_ATmega328 -DARDUINO_ARCH_AVR -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/cores/MCUdude_corefiles -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/variants/standard -I/Users/lee/Documents/Arduino/libraries/Bounce2/src -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/libraries/EEPROM/src /var/folders/kz/yg8fjhp53c3201sw0bhpccy40000gn/T/arduino_build_304102/sketch/fvduino.ino.cpp -o /var/folders/kz/yg8fjhp53c3201sw0bhpccy40000gn/T/arduino_build_304102/preproc/ctags_target_for_gcc_minus_e.cpp -DARDUINO_LIB_DISCOVERY_PHASE
/Applications/Arduino.app/Contents/Java/tools-builder/ctags/5.8-arduino11/ctags -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives /var/folders/kz/yg8fjhp53c3201sw0bhpccy40000gn/T/arduino_build_304102/preproc/ctags_target_for_gcc_minus_e.cpp
Compiling sketch...
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10813 -DARDUINO_AVR_ATmega328 -DARDUINO_ARCH_AVR -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/cores/MCUdude_corefiles -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/variants/standard -I/Users/lee/Documents/Arduino/libraries/Bounce2/src -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/libraries/EEPROM/src /var/folders/kz/yg8fjhp53c3201sw0bhpccy40000gn/T/arduino_build_304102/sketch/oled.cpp -o /var/folders/kz/yg8fjhp53c3201sw0bhpccy40000gn/T/arduino_build_304102/sketch/oled.cpp.o
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10813 -DARDUINO_AVR_ATmega328 -DARDUINO_ARCH_AVR -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/cores/MCUdude_corefiles -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/variants/standard -I/Users/lee/Documents/Arduino/libraries/Bounce2/src -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/libraries/EEPROM/src /var/folders/kz/yg8fjhp53c3201sw0bhpccy40000gn/T/arduino_build_304102/sketch/fvduino.ino.cpp -o /var/folders/kz/yg8fjhp53c3201sw0bhpccy40000gn/T/arduino_build_304102/sketch/fvduino.ino.cpp.o
fvduino:324:1: error: 'Button' does not name a type; did you mean 'ultoa'?
 Button select_button = Button();
 ^~~~~~
 ultoa
fvduino:325:1: error: 'Button' does not name a type; did you mean 'ultoa'?
 Button save_button = Button();
 ^~~~~~
 ultoa
fvduino:326:1: error: 'Button' does not name a type; did you mean 'ultoa'?
 Button fast_button = Button();
 ^~~~~~
 ultoa
fvduino:327:1: error: 'Button' does not name a type; did you mean 'ultoa'?
 Button footswitch = Button();
 ^~~~~~
 ultoa
/Users/lee/Desktop/fvduino-main/fvduino/fvduino.ino: In function 'void setup()':
fvduino:812:3: error: 'select_button' was not declared in this scope
   select_button.attach(SELE_BUT_PIN, INPUT);
   ^~~~~~~~~~~~~
/Users/lee/Desktop/fvduino-main/fvduino/fvduino.ino:812:3: note: suggested alternative: 'selection'
   select_button.attach(SELE_BUT_PIN, INPUT);
   ^~~~~~~~~~~~~
   selection
fvduino:814:3: error: 'save_button' was not declared in this scope
   save_button.attach(SAVE_BUT_PIN, INPUT);
   ^~~~~~~~~~~
fvduino:816:3: error: 'fast_button' was not declared in this scope
   fast_button.attach(FAST_BUT_PIN, INPUT);
   ^~~~~~~~~~~
fvduino:818:3: error: 'footswitch' was not declared in this scope
   footswitch.attach(FOOT_BUT_PIN, INPUT);
   ^~~~~~~~~~
/Users/lee/Desktop/fvduino-main/fvduino/fvduino.ino:818:3: note: suggested alternative: 'rom_pitch'
   footswitch.attach(FOOT_BUT_PIN, INPUT);
   ^~~~~~~~~~
   rom_pitch
/Users/lee/Desktop/fvduino-main/fvduino/fvduino.ino: In function 'void loop()':
fvduino:948:3: error: 'select_button' was not declared in this scope
   select_button.update();
   ^~~~~~~~~~~~~
/Users/lee/Desktop/fvduino-main/fvduino/fvduino.ino:948:3: note: suggested alternative: 'selection'
   select_button.update();
   ^~~~~~~~~~~~~
   selection
fvduino:949:3: error: 'save_button' was not declared in this scope
   save_button.update();
   ^~~~~~~~~~~
fvduino:950:3: error: 'fast_button' was not declared in this scope
   fast_button.update();
   ^~~~~~~~~~~
fvduino:951:3: error: 'footswitch' was not declared in this scope
   footswitch.update();
   ^~~~~~~~~~
/Users/lee/Desktop/fvduino-main/fvduino/fvduino.ino:951:3: note: suggested alternative: 'rom_pitch'
   footswitch.update();
   ^~~~~~~~~~
   rom_pitch
Using library Bounce2 at version 2.53 in folder: /Users/lee/Documents/Arduino/libraries/Bounce2 
Using library EEPROM at version 2.0 in folder: /Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/libraries/EEPROM 
exit status 1
'Button' does not name a type; did you mean 'ultoa'?

`

**Comment by n3ws** [comment]
Hi,

thanks for trying out fvduino! You have to download the 
bounce2 library from https://github.com/thomasfredericks/Bounce2

The version in arduino IDE is missing funcionality.

**Comment by leetut** [comment]
same error with that bounce2 library

`Arduino: 1.8.13 (Mac OS X), Board: "ATmega328, Yes (UART0), EEPROM retained, 328P / 328PA, BOD 2.7V, LTO disabled, External 16 MHz"











/Applications/Arduino.app/Contents/Java/arduino-builder -dump-prefs -logger=machine -hardware /Applications/Arduino.app/Contents/Java/hardware -hardware /Users/lee/Library/Arduino15/packages -hardware /Users/lee/Documents/Arduino/hardware -tools /Applications/Arduino.app/Contents/Java/tools-builder -tools /Applications/Arduino.app/Contents/Java/hardware/tools/avr -tools /Users/lee/Library/Arduino15/packages -built-in-libraries /Applications/Arduino.app/Contents/Java/libraries -libraries /Users/lee/Documents/Arduino/libraries -fqbn=MiniCore:avr:328:bootloader=uart0,eeprom=keep,variant=modelP,BOD=2v7,LTO=Os,clock=16MHz_external -ide-version=10813 -build-path /var/folders/kz/yg8fjhp53c3201sw0bhpccy40000gn/T/arduino_build_881101 -warnings=none -build-cache /var/folders/kz/yg8fjhp53c3201sw0bhpccy40000gn/T/arduino_cache_158604 -prefs=build.warn_data_percentage=75 -verbose /Users/lee/Documents/Arduino/fvduino/fvduino.ino
/Applications/Arduino.app/Contents/Java/arduino-builder -compile -logger=machine -hardware /Applications/Arduino.app/Contents/Java/hardware -hardware /Users/lee/Library/Arduino15/packages -hardware /Users/lee/Documents/Arduino/hardware -tools /Applications/Arduino.app/Contents/Java/tools-builder -tools /Applications/Arduino.app/Contents/Java/hardware/tools/avr -tools /Users/lee/Library/Arduino15/packages -built-in-libraries /Applications/Arduino.app/Contents/Java/libraries -libraries /Users/lee/Documents/Arduino/libraries -fqbn=MiniCore:avr:328:bootloader=uart0,eeprom=keep,variant=modelP,BOD=2v7,LTO=Os,clock=16MHz_external -ide-version=10813 -build-path /var/folders/kz/yg8fjhp53c3201sw0bhpccy40000gn/T/arduino_build_881101 -warnings=none -build-cache /var/folders/kz/yg8fjhp53c3201sw0bhpccy40000gn/T/arduino_cache_158604 -prefs=build.warn_data_percentage=75 -verbose /Users/lee/Documents/Arduino/fvduino/fvduino.ino
Using board '328' from platform in folder: /Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6
Using core 'MCUdude_corefiles' from platform in folder: /Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6
Detecting libraries used...
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10813 -DARDUINO_AVR_ATmega328 -DARDUINO_ARCH_AVR -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/cores/MCUdude_corefiles -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/variants/standard /var/folders/kz/yg8fjhp53c3201sw0bhpccy40000gn/T/arduino_build_881101/sketch/fvduino.ino.cpp -o /dev/null -DARDUINO_LIB_DISCOVERY_PHASE
Alternatives for Bounce2.h: [Bounce2-master@2.56]
ResolveLibrary(Bounce2.h)
  -> candidates: [Bounce2-master@2.56]
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10813 -DARDUINO_AVR_ATmega328 -DARDUINO_ARCH_AVR -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/cores/MCUdude_corefiles -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/variants/standard -I/Users/lee/Documents/Arduino/libraries/Bounce2-master/src /var/folders/kz/yg8fjhp53c3201sw0bhpccy40000gn/T/arduino_build_881101/sketch/fvduino.ino.cpp -o /dev/null -DARDUINO_LIB_DISCOVERY_PHASE
Alternatives for EEPROM.h: [EEPROM@2.0]
ResolveLibrary(EEPROM.h)
  -> candidates: [EEPROM@2.0]
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10813 -DARDUINO_AVR_ATmega328 -DARDUINO_ARCH_AVR -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/cores/MCUdude_corefiles -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/variants/standard -I/Users/lee/Documents/Arduino/libraries/Bounce2-master/src -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/libraries/EEPROM/src /var/folders/kz/yg8fjhp53c3201sw0bhpccy40000gn/T/arduino_build_881101/sketch/fvduino.ino.cpp -o /dev/null -DARDUINO_LIB_DISCOVERY_PHASE
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10813 -DARDUINO_AVR_ATmega328 -DARDUINO_ARCH_AVR -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/cores/MCUdude_corefiles -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/variants/standard -I/Users/lee/Documents/Arduino/libraries/Bounce2-master/src -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/libraries/EEPROM/src /var/folders/kz/yg8fjhp53c3201sw0bhpccy40000gn/T/arduino_build_881101/sketch/oled.cpp -o /dev/null -DARDUINO_LIB_DISCOVERY_PHASE
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10813 -DARDUINO_AVR_ATmega328 -DARDUINO_ARCH_AVR -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/cores/MCUdude_corefiles -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/variants/standard -I/Users/lee/Documents/Arduino/libraries/Bounce2-master/src -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/libraries/EEPROM/src /Users/lee/Documents/Arduino/libraries/Bounce2-master/src/Bounce2.cpp -o /dev/null -DARDUINO_LIB_DISCOVERY_PHASE
Generating function prototypes...
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10813 -DARDUINO_AVR_ATmega328 -DARDUINO_ARCH_AVR -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/cores/MCUdude_corefiles -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/variants/standard -I/Users/lee/Documents/Arduino/libraries/Bounce2-master/src -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/libraries/EEPROM/src /var/folders/kz/yg8fjhp53c3201sw0bhpccy40000gn/T/arduino_build_881101/sketch/fvduino.ino.cpp -o /var/folders/kz/yg8fjhp53c3201sw0bhpccy40000gn/T/arduino_build_881101/preproc/ctags_target_for_gcc_minus_e.cpp -DARDUINO_LIB_DISCOVERY_PHASE
/Applications/Arduino.app/Contents/Java/tools-builder/ctags/5.8-arduino11/ctags -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives /var/folders/kz/yg8fjhp53c3201sw0bhpccy40000gn/T/arduino_build_881101/preproc/ctags_target_for_gcc_minus_e.cpp
Compiling sketch...
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10813 -DARDUINO_AVR_ATmega328 -DARDUINO_ARCH_AVR -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/cores/MCUdude_corefiles -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/variants/standard -I/Users/lee/Documents/Arduino/libraries/Bounce2-master/src -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/libraries/EEPROM/src /var/folders/kz/yg8fjhp53c3201sw0bhpccy40000gn/T/arduino_build_881101/sketch/fvduino.ino.cpp -o /var/folders/kz/yg8fjhp53c3201sw0bhpccy40000gn/T/arduino_build_881101/sketch/fvduino.ino.cpp.o
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10813 -DARDUINO_AVR_ATmega328 -DARDUINO_ARCH_AVR -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/cores/MCUdude_corefiles -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/variants/standard -I/Users/lee/Documents/Arduino/libraries/Bounce2-master/src -I/Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/libraries/EEPROM/src /var/folders/kz/yg8fjhp53c3201sw0bhpccy40000gn/T/arduino_build_881101/sketch/oled.cpp -o /var/folders/kz/yg8fjhp53c3201sw0bhpccy40000gn/T/arduino_build_881101/sketch/oled.cpp.o
fvduino:324:1: error: 'Button' does not name a type; did you mean 'ultoa'?
 Button select_button = Button();
 ^~~~~~
 ultoa
fvduino:325:1: error: 'Button' does not name a type; did you mean 'ultoa'?
 Button save_button = Button();
 ^~~~~~
 ultoa
fvduino:326:1: error: 'Button' does not name a type; did you mean 'ultoa'?
 Button fast_button = Button();
 ^~~~~~
 ultoa
fvduino:327:1: error: 'Button' does not name a type; did you mean 'ultoa'?
 Button footswitch = Button();
 ^~~~~~
 ultoa
/Users/lee/Documents/Arduino/fvduino/fvduino.ino: In function 'void setup()':
fvduino:812:3: error: 'select_button' was not declared in this scope
   select_button.attach(SELE_BUT_PIN, INPUT);
   ^~~~~~~~~~~~~
/Users/lee/Documents/Arduino/fvduino/fvduino.ino:812:3: note: suggested alternative: 'selection'
   select_button.attach(SELE_BUT_PIN, INPUT);
   ^~~~~~~~~~~~~
   selection
fvduino:814:3: error: 'save_button' was not declared in this scope
   save_button.attach(SAVE_BUT_PIN, INPUT);
   ^~~~~~~~~~~
fvduino:816:3: error: 'fast_button' was not declared in this scope
   fast_button.attach(FAST_BUT_PIN, INPUT);
   ^~~~~~~~~~~
fvduino:818:3: error: 'footswitch' was not declared in this scope
   footswitch.attach(FOOT_BUT_PIN, INPUT);
   ^~~~~~~~~~
/Users/lee/Documents/Arduino/fvduino/fvduino.ino:818:3: note: suggested alternative: 'rom_pitch'
   footswitch.attach(FOOT_BUT_PIN, INPUT);
   ^~~~~~~~~~
   rom_pitch
/Users/lee/Documents/Arduino/fvduino/fvduino.ino: In function 'void loop()':
fvduino:948:3: error: 'select_button' was not declared in this scope
   select_button.update();
   ^~~~~~~~~~~~~
/Users/lee/Documents/Arduino/fvduino/fvduino.ino:948:3: note: suggested alternative: 'selection'
   select_button.update();
   ^~~~~~~~~~~~~
   selection
fvduino:949:3: error: 'save_button' was not declared in this scope
   save_button.update();
   ^~~~~~~~~~~
fvduino:950:3: error: 'fast_button' was not declared in this scope
   fast_button.update();
   ^~~~~~~~~~~
fvduino:951:3: error: 'footswitch' was not declared in this scope
   footswitch.update();
   ^~~~~~~~~~
/Users/lee/Documents/Arduino/fvduino/fvduino.ino:951:3: note: suggested alternative: 'rom_pitch'
   footswitch.update();
   ^~~~~~~~~~
   rom_pitch
Using library Bounce2-master at version 2.56 in folder: /Users/lee/Documents/Arduino/libraries/Bounce2-master 
Using library EEPROM at version 2.0 in folder: /Users/lee/Library/Arduino15/packages/MiniCore/hardware/avr/2.0.6/libraries/EEPROM 
exit status 1
'Button' does not name a type; did you mean 'ultoa'?
Invalid library found in /Users/lee/Documents/Arduino/libraries/libmaple-master: no headers files (.h) found in /Users/lee/Documents/Arduino/libraries/libmaple-master
`

**Comment by n3ws** [comment]
Looks like the Bounce2 library has been updated.
Class Button is now part of Bounce2 namespace.

Try changing Button declarations to Bounce2::Button

**Comment by n3ws** [comment]
Updated fvduino
